#pragma once

#include <ft/ft_entry.h>
#include <ft/ft_outside_event_presenter.h>
#include <ft/ft_value_accesser.h>
#include <mt/mt_vector.h>
#include <so/stageobject.h>
#include <types.h>

class itCustomizerInterface;
class ftOwner;

class Fighter : public StageObject, public soStatusEventObserver, public soSituationEventObserver, public soCollisionAttackEventObserver, public soCollisionHitEventObserver, public soCollisionShieldEventObserver, public soCollisionReflectorEventObserver, public soCollisionAbsorberEventObserver, public soCollisionSearchEventObserver, public soCaptureEventObserver, public soItemManageEventObserver, public soMotionEventObserver, public soDamageEventObserver, public ftEntryEventObserver, public soTurnEventObserver {
public:
    enum StatusKind {
        Status_Wait = 0x0,
        Status_Walk = 0x1,
        Status_Walk_Brake = 0x2,
        Status_Dash = 0x3,
        Status_Run = 0x4,
        Status_Run_Brake = 0x5,
        Status_Turn = 0x6,
        Status_Turn_Dash = 0x7,
        Status_Turn_Run = 0x8,
        Status_Turn_Run_Brake = 0x9,
        Status_Jump_Squat = 0xA,
        Status_Jump = 0xB,
        Status_Jump_Aerial = 0xC,
        Status_Fly = 0xD,
        Status_Fall = 0xE,
        Status_Fall_Aerial = 0xF,
        Status_Fall_Special = 0x10,
        Status_Squat = 0x11,
        Status_Squat_Wait = 0x12,
        Status_Squat_F = 0x13,
        Status_Squat_B = 0x14,
        Status_Squat_Rv = 0x15,
        Status_Landing = 0x16,
        Status_Landing_Light = 0x17,
        Status_Landing_Attack_Air = 0x18,
        Status_Landing_Fall_Special = 0x19,
        Status_Guard_On = 0x1A,
        Status_Guard = 0x1B,
        Status_Guard_Off = 0x1C,
        Status_Guard_Damage = 0x1D,
        Status_Escape = 0x1E,
        Status_Escape_F = 0x1F,
        Status_Escape_B = 0x20,
        Status_Escape_Air = 0x21,
        Status_Rebound_Stop = 0x22,
        Status_Rebound = 0x23,
        Status_Attack = 0x24,
        Status_Attack_100 = 0x25,
        Status_Attack_Dash = 0x26,
        Status_Attack_S3 = 0x27,
        Status_Attack_Hi3 = 0x28,
        Status_Attack_Lw3 = 0x29,
        Status_Attack_S4_Start = 0x2A,
        Status_Attack_S4_Hold = 0x2B,
        Status_Attack_S4 = 0x2C,
        Status_Attack_Lw4_Start = 0x2D,
        Status_Attack_Lw4_Hold = 0x2E,
        Status_Attack_Lw4 = 0x2F,
        Status_Attack_Hi4_Start = 0x30,
        Status_Attack_Hi4_Hold = 0x31,
        Status_Attack_Hi4 = 0x32,
        Status_Attack_Air = 0x33,
        Status_Catch = 0x34,
        Status_Catch_Pull = 0x35,
        Status_Catch_Dash = 0x36,
        Status_Catch_Dash_Pull = 0x37,
        Status_Catch_Turn = 0x38,
        Status_Catch_Wait = 0x39,
        Status_Catch_Attack = 0x3A,
        Status_Catch_Cut = 0x3B,
        Status_Throw = 0x3C,
        Status_Capture_Pulled = 0x3D,
        Status_Capture_Wait = 0x3E,
        Status_Capture_Damage = 0x3F,
        Status_Capture_Cut = 0x40,
        Status_Capture_Jump = 0x41,
        Status_Capture_Thrown = 0x42,
        Status_Damage = 0x43,
        Status_Damage_Air = 0x44,
        Status_Damage_Fly = 0x45,
        Status_Damage_Fly_Roll = 0x46,
        Status_Damage_Fly_Reflect_Lr = 0x47,
        Status_Damage_Fly_Reflect_U = 0x48,
        Status_Damage_Fall = 0x49,
        Status_Down = 0x4A,
        Status_Down_Spot = 0x4B,
        Status_Down_Continue = 0x4C,
        Status_Down_Wait = 0x4D,
        Status_Down_Wait_Continue = 0x4E,
        Status_Down_Eat = 0x4F,
        Status_Lay_Down = 0x50,
        Status_Down_Stand = 0x51,
        Status_Down_Stand_Fb = 0x52,
        Status_Down_Stand_Attack = 0x53,
        Status_Down_Damage = 0x54,
        Status_Down_Reflect_Lr = 0x55,
        Status_Shield_Break_Fly = 0x56,
        Status_Shield_Break_Fall = 0x57,
        Status_Shield_Break_Down = 0x58,
        Status_FuraFura_Stand = 0x59,
        Status_FuraFura = 0x5A,
        Status_FuraFura_End = 0x5B,
        Status_Damage_Song_Start = 0x5C,
        Status_Damage_Song = 0x5D,
        Status_Damage_Song_End = 0x5E,
        Status_Bind = 0x5F,
        Status_Passive = 0x60,
        Status_Passive_Fb = 0x61,
        Status_Passive_Wall = 0x62,
        Status_Passive_Wall_Jump = 0x63,
        Status_Passive_Ceil = 0x64,
        Status_Stop_Wall = 0x65,
        Status_Stop_Ceil = 0x66,
        Status_Wall_Jump = 0x67,
        Status_Attach_Wall = 0x68,
        Status_Attach_Wall_Wait = 0x69,
        Status_Detach_Wall = 0x6A,
        Status_Detach_Wall_Fall = 0x6B,
        Status_Detach_Wall_Jump = 0x6C,
        Status_Tread_Jump = 0x6D,
        Status_Tread_Damage = 0x6E,
        Status_Tread_Damage_Rv = 0x6F,
        Status_Tread_Damage_Air = 0x70,
        Status_Tread_Fall = 0x71,
        Status_Pass = 0x72,
        Status_Cliff_Catch_Move = 0x73,
        Status_Cliff_Catch = 0x74,
        Status_Cliff_Wait = 0x75,
        Status_Cliff_Attack = 0x76,
        Status_Cliff_Climb = 0x77,
        Status_Cliff_Escape = 0x78,
        Status_Cliff_Jump1 = 0x79,
        Status_Cliff_Jump2 = 0x7A,
        Status_Cliff_Jump3 = 0x7B,
        Status_Ottoto = 0x7C,
        Status_Ottoto_Wait = 0x7D,
        Status_Miss_Foot = 0x7E,
        Status_Air_Lasso = 0x7F,
        Status_Air_Lasso_Reach = 0x80,
        Status_Air_Lasso_Hang = 0x81,
        Status_Air_Lasso_Rewind = 0x82,
        Status_Air_Lasso_Failure = 0x83,
        Status_Glide_Start = 0x84,
        Status_Glide = 0x85,
        Status_Glide_Landing = 0x86,
        Status_Glide_Attack = 0x87,
        Status_Glide_End = 0x88,
        Status_Slip = 0x89,
        Status_Slip_Down = 0x8A,
        Status_Slip_Turn = 0x8B,
        Status_Slip_Dash = 0x8C,
        Status_Slip_Wait = 0x8D,
        Status_Slip_Stand = 0x8E,
        Status_Slip_Stand_Attack = 0x8F,
        Status_Slip_Stand_F = 0x90,
        Status_Slip_Stand_B = 0x91,
        Status_Ladder_Catch = 0x92,
        Status_Ladder_Catch_End = 0x93,
        Status_Ladder_Wait = 0x94,
        Status_Ladder_End = 0x95,
        Status_Item_Pickup_Light = 0x96,
        Status_Item_Pickup_Heavy = 0x97,
        Status_Item_Lift_Wait = 0x98,
        Status_Item_Lift_Turn = 0x99,
        Status_Item_Lift_Walk = 0x9A,
        Status_Item_Throw = 0x9B,
        Status_Item_Throw_Dash = 0x9C,
        Status_Item_Throw_Heavy = 0x9D,
        Status_Item_Swing = 0x9E,
        Status_Item_Swing_S3 = 0x9F,
        Status_Item_Swing_S4_Start = 0xA0,
        Status_Item_Swing_S4 = 0xA1,
        Status_Item_Swing_S4_Hold = 0xA2,
        Status_Item_Swing_Dash = 0xA3,
        Status_Item_Shoot_Wait = 0xA4,
        Status_Item_Shoot_Walk_F = 0xA5,
        Status_Item_Shoot_Walk_Brake_F = 0xA6,
        Status_Item_Shoot_Walk_B = 0xA7,
        Status_Item_Shoot_Walk_Brake_B = 0xA8,
        Status_Item_Shoot_Dash_F = 0xA9,
        Status_Item_Shoot_Dash_B = 0xAA,
        Status_Item_Shoot_Jump_Squat = 0xAB,
        Status_Item_Shoot_Jump = 0xAC,
        Status_Item_Shoot_Air = 0xAD,
        Status_Item_Shoot_Landing = 0xAE,
        Status_Item_Screw_Jump = 0xAF,
        Status_Item_Screw_Jump_Aerial = 0xB0,
        Status_Item_Screw_Fall = 0xB1,
        Status_Item_Assist_Hoist = 0xB2,
        Status_Swim_Dive = 0xB3,
        Status_Swim_Rise = 0xB4,
        Status_Swim_Up = 0xB5,
        Status_Swim_Wait = 0xB6,
        Status_Swim = 0xB7,
        Status_Swim_End = 0xB8,
        Status_Swim_Turn = 0xB9,
        Status_Swim_Jump = 0xBA,
        Status_Swim_Drown = 0xBB,
        Status_Swim_Drown_Out = 0xBC,
        Status_Dead = 0xBD,
        Status_Rebirth = 0xBE,
        Status_Gimmick_Door = 0xBF,
        Status_Gimmick_Barrel = 0xC0,
        Status_Gimmick_Catapult = 0xC1,
        Status_Gimmick_Truck = 0xC2,
        Status_Gimmick_Spring = 0xC3,
        Status_Gimmick_Spring_Jump = 0xC4,
        Status_Gimmick_Spring_Back = 0xC5,
        Status_Gimmick_Eaten = 0xC6,
        Status_Bury = 0xC7,
        Status_Bury_Wait = 0xC8,
        Status_Bury_Jump = 0xC9,
        Status_Ice = 0xCA,
        Status_Ice_Jump = 0xCB,
        Status_Bitten_Wario_Start = 0xCC,
        Status_Bitten_Wario = 0xCD,
        Status_Bitten_Wario_End = 0xCE,
        Status_Clung_Captain = 0xCF,
        Status_Swallowed = 0xD0,
        Status_Swallowed_Drink = 0xD1,
        Status_Swallowed_Capture = 0xD2,
        Status_Swallowed_Thrown_Star = 0xD3,
        Status_Swallowed_Thrown = 0xD4,
        Status_Swallowed_Canceled = 0xD5,
        Status_Clung_Diddy = 0xD6,
        Status_Clung_Damage_Diddy = 0xD7,
        Status_Clung_Thrown_Diddy = 0xD8,
        Status_Shouldered_Donkey_Start = 0xD9,
        Status_Shouldered_Donkey = 0xDA,
        Status_Shouldered_Donkey_Thrown = 0xDB,
        Status_Warptar = 0xDC,
        Status_Warpstar_Jump = 0xDD,
        Status_Dragoon_Ride = 0xDE,
        Status_Hammer_Wait = 0xDF,
        Status_Hammer_Walk = 0xE0,
        Status_Hammer_Turn = 0xE1,
        Status_Hammer_Jump_Squat = 0xE2,
        Status_Hammer_Jump = 0xE3,
        Status_Hammer_Fall = 0xE4,
        Status_Hammer_Landing = 0xE5,
        Status_Clung_Ganon = 0xE6,
        Status_Catched_Ganon = 0xE7,
        Status_Catched_Air_Ganon = 0xE8,
        Status_Catched_Air_Fall_Ganon = 0xE9,
        Status_Catched_Air_End_Ganon = 0xEA,
        Status_Capture_Yoshi = 0xEB,
        Status_Yoshi_Egg = 0xEC,
        Status_Link_Final = 0xED,
        Status_Koopa_Dived = 0xEE,

        Status_Pit_Fall = 0xF0,
        Status_Throw_Kirby = 0xF1,
        Status_Big = 0xF2,
        Status_Small = 0xF3,
        Status_Heart_Swap = 0xF4,
        Status_Heart_Swap_End = 0xF5,
        Status_Adv_Follow = 0xF6,
        Status_Ike_Final_Damage_Fly = 0xF7,
        Status_Ike_Final_Damage = 0xF8,
        Status_Ike_Final_Damage_Fall = 0xF9,
        Status_Capture_Masterhand = 0xFA,
        Status_Final_Visual_Attack_Other = 0xFB,
        Status_Captain_Final_Start = 0xFC,
        Status_Captain_Final_FuraFura = 0xFD,
        Status_Captain_Final_Clash = 0xFE,
        Status_Captain_Final_End = 0xFF,
        Status_Kirby_Final_Damage_Fly = 0x100,
        Status_Kirby_Final_Damage_Wait = 0x101,
        Status_Capture_Gokulin = 0x102,
        Status_Capture_Cut_Gokulin = 0x103,
        Status_Capture_Taboo = 0x104,
        Status_Capture_Bucyulus = 0x105,
        Status_Capture_Cut_Bucyulus = 0x106,
        Status_Capture_Pulled_Yoshi = 0x107,
        Status_Capture_Wait_Yoshi = 0x108,
        Status_Capture_Damage_Yoshi = 0x109,

        Status_Standby = 0x10B,
        Status_Appeal  = 0x10C,
        Status_Smash_Appeal = 0x10D,
        Status_Entry = 0x10E,
        Status_Win = 0x10F,
        Status_Lose = 0x110,
        Status_Test_Motion = 0x111
    };

    enum MotionKind {
        Motion_Wait_1 = 0x0,
        Motion_Wait_2 = 0x1,
        Motion_Wait_3 = 0x2,
        Motion_Tex_Anim = 0x3,

        Motion_Wait_Item = 0x5,
        Motion_Item_Hand_Pickup = 0x6,
        Motion_Item_Hand_Have = 0x7,
        Motion_Item_Hand_Grip = 0x8,
        Motion_Item_Hand_Smash = 0x9,
        Motion_Walk_Slow = 0xA,
        Motion_Walk_Middle = 0xB,
        Motion_Walk_Fast = 0xC,
        Motion_Walk_Brake = 0xD,
        Motion_Dash = 0xE,
        Motion_Run = 0xF,
        Motion_Run_Brake = 0x10,
        Motion_Turn = 0x11,
        Motion_Turn_Run = 0x12,
        Motion_Turn_Run_Brake = 0x13,
        Motion_Jump_Squat = 0x14,
        Motion_Jump_F = 0x15,
        Motion_Jump_F_ = 0x16,
        Motion_Jump_B = 0x17,
        Motion_Jump_B_ = 0x18,
        Motion_Jump_Aerial_F = 0x19,
        Motion_Jump_Aerial_B = 0x1A,
        Motion_Special_N_Cancel = 0x1B,
        Motion_Special_Air_N_Cancel = 0x1C,
        Motion_Appeal_Brawl_Lw_R = 0x1D,
        Motion_Appeal_Brawl_Lw_L = 0x1E,
        Motion_Appeal_Brawl_S = 0x1F,
        Motion_Fall = 0x20,
        Motion_Fall_F = 0x21,
        Motion_Fall_B = 0x22,
        Motion_Fall_Aerial = 0x23,
        Motion_Fall_Aerial_F = 0x24,
        Motion_Fall_Aerial_B = 0x25,
        Motion_Fall_Special = 0x26,
        Motion_Fall_Special_F = 0x27,
        Motion_Fall_Special_B = 0x28,
        Motion_Damage_Fall = 0x29,
        Motion_Squat = 0x2A,
        Motion_Squat_Wait = 0x2B,
        Motion_Squat_Wait_2 = 0x2C,
        Motion_Squat_Wait_Item = 0x2D,
        Motion_Squat_F = 0x2E,
        Motion_Squat_B = 0x2F,
        Motion_Squat_Rv = 0x30,
        Motion_Landing_Light = 0x31,
        Motion_Landing_Heavy = 0x32,
        Motion_Landing_Fall_Special = 0x33,
        Motion_Step_Jump = 0x34,
        Motion_Step_Pose = 0x35,
        Motion_Step_Back = 0x36,
        Motion_Step_Air_Pose = 0x37,
        Motion_Step_Fall = 0x38,
        Motion_Glide_Start = 0x39,
        Motion_Glide_Direction = 0x3A,
        Motion_Glide_Wing = 0x3B,
        Motion_Glide_Attack = 0x3C,
        Motion_Glide_End = 0x3D,
        Motion_Glide_Landing = 0x3E,
        Motion_Guard_On = 0x3F,
        Motion_Guard = 0x40,
        Motion_Guard_Off = 0x41,
        Motion_Guard_Damage = 0x42,
        Motion_Escape_N = 0x43,
        Motion_Escape_F = 0x44,
        Motion_Escape_B = 0x45,
        Motion_Escape_Air = 0x46,
        Motion_Rebound = 0x47,
        Motion_Attack_11 = 0x48,
        Motion_Attack_12 = 0x49,
        Motion_Attack_13 = 0x4A,
        Motion_Attack_100_Start = 0x4B,
        Motion_Attack_100 = 0x4C,
        Motion_Attack_End = 0x4D,
        Motion_Attack_Dash = 0x4E,
        Motion_Attack_S3_Hi = 0x4F,
        Motion_Attack_S3_S = 0x50,
        Motion_Attack_Dash_Air = 0x51,

        Motion_Attack_S3_Lw = 0x53,
        Motion_Attack_Hi_3 = 0x54,
        Motion_Attack_Lw_3 = 0x55,
        Motion_Attack_S4_Start = 0x56,
        Motion_Attack_S4_Hi = 0x57,
        Motion_Attack_S4_S = 0x58,

        Motion_Attack_S4_Lw = 0x5A,
        Motion_Attack_S4_Hold = 0x5B,
        Motion_Attack_Hi_4_Start = 0x5C,
        Motion_Attack_Hi_4 = 0x5D,
        Motion_Attack_Hi_4_Hold = 0x5E,
        Motion_Attack_Lw_4_Start = 0x5F,
        Motion_Attack_Lw_4 = 0x60,
        Motion_Attack_Lw_4_Hold = 0x61,
        Motion_Attack_Air_N = 0x62,
        Motion_Attack_Air_F = 0x63,
        Motion_Attack_Air_B = 0x64,
        Motion_Attack_Air_Hi = 0x65,
        Motion_Attack_Air_Lw = 0x66,
        Motion_Landing_Air_N = 0x67,
        Motion_Landing_Air_F = 0x68,
        Motion_Landing_Air_B = 0x69,
        Motion_Landing_Air_Hi = 0x6A,
        Motion_Landing_Air_Lw = 0x6B,
        Motion_Catch = 0x6C,
        Motion_Catch_Dash = 0x6D,
        Motion_Catch_Turn = 0x6E,
        Motion_Catch_Wait = 0x6F,
        Motion_Catch_Attack = 0x70,
        Motion_Catch_Cut = 0x71,
        Motion_Throw_B = 0x72,
        Motion_Throw_F = 0x73,
        Motion_Throw_Hi = 0x74,
        Motion_Throw_Lw = 0x75,
        Motion_Thrown_B = 0x76,
        Motion_Thrown_F = 0x77,
        Motion_Thrown_Hi = 0x78,
        Motion_Thrown_Lw = 0x79,
        Motion_Thrown_Dx_B = 0x7A,
        Motion_Thrown_Dx_F = 0x7B,
        Motion_Thrown_Dx_Hi = 0x7C,
        Motion_Thrown_Dx_Lw = 0x7D,
        Motion_Capture_Pulled_Hi = 0x7E,
        Motion_Capture_Wait_Hi = 0x7F,
        Motion_Capture_Damage_Hi = 0x80,
        Motion_Capture_Pulled_Lw = 0x81,
        Motion_Capture_Wait_Lw = 0x82,
        Motion_Capture_Damage_Lw = 0x83,
        Motion_Capture_Pulled_Snake = 0x84,
        Motion_Capture_Wait_Snake = 0x85,
        Motion_Capture_Damage_Snake = 0x86,
        Motion_Capture_Pulled_Snake_ = 0x87,
        Motion_Capture_Wait_Snake_ = 0x88,
        Motion_Capture_Damage_Snake_ = 0x89,
        Motion_Capture_Pulled_Dx_Snake = 0x8A,
        Motion_Capture_Wait_Dx_Snake = 0x8B,
        Motion_Capture_Damage_Dx_Snake = 0x8C,
        Motion_Capture_Pulled_Dx_Snake_ = 0x8D,
        Motion_Capture_Wait_Dx_Snake_ = 0x8E,
        Motion_Capture_Damage_Dx_Snake_ = 0x8F,
        Motion_Capture_Pulled_Big_Snake = 0x90,
        Motion_Capture_Wait_Big_Snake = 0x91,
        Motion_Capture_Damage_Big_Snake = 0x92,
        Motion_Capture_Pulled_Big_Snake_ = 0x93,
        Motion_Capture_Wait_Big_Snake_ = 0x94,
        Motion_Capture_Damage_Big_Snake_ = 0x95,
        Motion_Capture_Cut = 0x96,
        Motion_Capture_Jump = 0x97,
        Motion_Damage_Hi_1 = 0x98,
        Motion_Damage_Hi_2 = 0x99,
        Motion_Damage_Hi_3 = 0x9A,
        Motion_Damage_N_1 = 0x9B,
        Motion_Damage_N_2 = 0x9C,
        Motion_Damage_N_3 = 0x9D,
        Motion_Damage_Lw_1 = 0x9E,
        Motion_Damage_Lw_2 = 0x9F,
        Motion_Damage_Lw_3 = 0xA0,
        Motion_Damage_Air_1 = 0xA1,
        Motion_Damage_Air_2 = 0xA2,
        Motion_Damage_Air_3 = 0xA3,
        Motion_Damage_Fly_Hi = 0xA4,
        Motion_Damage_Fly_N = 0xA5,
        Motion_Damage_Fly_Lw = 0xA6,
        Motion_Damage_Fly_Top = 0xA7,
        Motion_Damage_Fly_Roll = 0xA8,
        Motion_Damage_Elec = 0xA9,
        Motion_Down_Bound_U = 0xAA,
        Motion_Down_Wait_U = 0xAB,
        Motion_Down_Damage_U = 0xAC,
        Motion_Down_Damage_U_3 = 0xAD,
        Motion_Down_Eat_U = 0xAE,
        Motion_Down_Stand_U = 0xAF,
        Motion_Down_Attack_U = 0xB0,
        Motion_Down_Forward_U = 0xB1,
        Motion_Down_Back_U = 0xB2,
        Motion_Down_Bound_D = 0xB3,
        Motion_Down_Wait_D = 0xB4,
        Motion_Down_Damage_D = 0xB5,
        Motion_Down_Damage_D_3 = 0xB6,
        Motion_Down_Eat_D = 0xB7,
        Motion_Down_Stand_D = 0xB8,
        Motion_Down_Attack_D = 0xB9,
        Motion_Down_Forward_D = 0xBA,
        Motion_Down_Back_D = 0xBB,
        Motion_Down_Spot_U = 0xBC,
        Motion_Down_Spot_D = 0xBD,
        Motion_Passive = 0xBE,
        Motion_Passive_Stand_F = 0xBF,
        Motion_Passive_Stand_B = 0xC0,
        Motion_Passive_Wall = 0xC1,
        Motion_Passive_Wall_Jump = 0xC2,
        Motion_Passive_Ceil = 0xC3,
        Motion_Passive_Wall_Attach = 0xC4,
        Motion_FuraFura = 0xC5,
        Motion_FuraFura_Start_U = 0xC6,
        Motion_FuraFura_Start_D = 0xC7,
        Motion_FuraFura_End = 0xC8,
        Motion_Fura_Sleep_Start = 0xC9,
        Motion_Fura_Sleep_Loop = 0xCA,
        Motion_Fura_Sleep_End = 0xCB,
        Motion_Swallowed = 0xCC,
        Motion_Pass = 0xCD,
        Motion_Ottotto = 0xCE,
        Motion_Ottotto_Wait = 0xCF,
        Motion_Wall_Damage = 0xD0,
        Motion_Stop_Ceil = 0xD1,
        Motion_Stop_Wall = 0xD2,
        Motion_Stop_Ceil_ = 0xD3,
        Motion_Miss_Foot = 0xD4,
        Motion_Cliff_Catch = 0xD5,
        Motion_Cliff_Wait = 0xD6,
        Motion_Cliff_Attack_Quick = 0xD7,
        Motion_Cliff_Climb_Quick = 0xD8,
        Motion_Cliff_Escape_Quick = 0xD9,
        Motion_Cliff_Jump_Quick_1 = 0xDA,
        Motion_Cliff_Jump_Quick_2 = 0xDB,
        Motion_Cliff_Attack_Slow = 0xDC,
        Motion_Cliff_Climb_Slow = 0xDD,
        Motion_Cliff_Escape_Slow = 0xDE,
        Motion_Cliff_Jump_Slow_1 = 0xDF,
        Motion_Cliff_Jump_Slow_2 = 0xE0,
        Motion_Slip_Down = 0xE1,
        Motion_Slip = 0xE2,
        Motion_Slip_Turn = 0xE3,
        Motion_Slip_Dash = 0xE4,
        Motion_Slip_Wait = 0xE5,
        Motion_Slip_Stand = 0xE6,
        Motion_Slip_Attack = 0xE7,
        Motion_Slip_Escape_F = 0xE8,
        Motion_Slip_Escape_B = 0xE9,
        Motion_Air_Catch = 0xEA,
        Motion_Air_Catch_Pose = 0xEB,
        Motion_Air_Catch_Hit = 0xEC,
        Motion_Air_Catch_ = 0xED,
        Motion_Swim_Rise = 0xEE,
        Motion_Swim_Up = 0xEF,
        Motion_Swim_Up_Damage = 0xF0,
        Motion_Swim = 0xF1,
        Motion_Swim_F = 0xF2,
        Motion_Swim_End = 0xF3,
        Motion_Swim_Turn = 0xF4,
        Motion_Swim_Drown = 0xF5,
        Motion_Swim_Drown_Out = 0xF6,
        Motion_Light_Get = 0xF7,
        Motion_Light_Walk_Get = 0xF8,
        Motion_Light_Eat = 0xF9,
        Motion_Walk_Eat = 0xFA,
        Motion_Heavy_Get = 0xFB,
        Motion_Heavy_Walk_1 = 0xFC,
        Motion_Heavy_Walk_2 = 0xFD,
        Motion_Light_Throw_Drop = 0xFE,
        Motion_Light_Throw_F = 0xFF,
        Motion_Light_Throw_B = 0x100,
        Motion_Light_Throw_Hi = 0x101,
        Motion_Light_Throw_Lw = 0x102,
        Motion_Light_Throw_F_ = 0x103,
        Motion_Light_Throw_B_ = 0x104,
        Motion_Light_Throw_Hi_ = 0x105,
        Motion_Light_Throw_Lw_ = 0x106,
        Motion_Light_Throw_Dash = 0x107,
        Motion_Light_Throw_Air_F = 0x108,
        Motion_Light_Throw_Air_B = 0x109,
        Motion_Light_Throw_Air_Hi = 0x10A,
        Motion_Light_Throw_Air_Lw = 0x10B,
        Motion_Light_Throw_Air_F_ = 0x10C,
        Motion_Light_Throw_Air_B_ = 0x10D,
        Motion_Light_Throw_Air_Hi_ = 0x10E,
        Motion_Light_Throw_Air_Lw_ = 0x10F,
        Motion_Heavy_Throw_F = 0x110,
        Motion_Heavy_Throw_B = 0x111,
        Motion_Heavy_Throw_Hi = 0x112,
        Motion_Heavy_Throw_Lw = 0x113,
        Motion_Heavy_Throw_F_ = 0x114,
        Motion_Heavy_Throw_B_ = 0x115,
        Motion_Heavy_Throw_Hi_ = 0x116,
        Motion_Heavy_Throw_Lw_ = 0x117,
        Motion_Smash_Throw_F = 0x118,
        Motion_Smash_Throw_B = 0x119,
        Motion_Smash_Throw_Hi = 0x11A,
        Motion_Smash_Throw_Lw = 0x11B,
        Motion_Smash_Throw_Dash = 0x11C,
        Motion_Smash_Throw_Air_F = 0x11D,
        Motion_Smash_Throw_Air_B = 0x11E,
        Motion_Smash_Throw_Air_Hi = 0x11F,
        Motion_Smash_Throw_Air_Lw = 0x120,
        Motion_Swing_1_Sword = 0x121,
        Motion_Swing_3_Sword = 0x122,
        Motion_Swing_4_Start_Sword = 0x123,
        Motion_Swing_4_Sword = 0x124,
        Motion_Swing_4_2_Sword = 0x125,
        Motion_Swing_4_Hold_Sword = 0x126,
        Motion_Swing_Dash_Sword = 0x127,
        Motion_Swing_1_Bat = 0x128,
        Motion_Swing_3_Bat = 0x129,
        Motion_Swing_4_Bat = 0x12A,
        Motion_Swing_Dash_Bat = 0x12B,
        Motion_Swing_1_Harisen = 0x12C,
        Motion_Swing_3_Harisen = 0x12D,
        Motion_Swing_4_Start_Harisen = 0x12E,
        Motion_Swing_4_Harisen = 0x12F,
        Motion_Swing_4_2_Harisen = 0x130,
        Motion_Swing_4_Hold_Harisen = 0x131,
        Motion_Swing_Dash_Harisen = 0x132,
        Motion_Swing_1_StarRod = 0x133,
        Motion_Swing_3_StarRod = 0x134,
        Motion_Swing_4_Start_StarRod = 0x135,
        Motion_Swing_4_StarRod = 0x136,
        Motion_Swing_4_2_StarRod = 0x137,
        Motion_Swing_4_Hold_StarRod = 0x138,
        Motion_Swing_Dash_StarRod = 0x139,
        Motion_Swing_1_LipStick = 0x13A,
        Motion_Swing_3_LipStick = 0x13B,
        Motion_Swing_4_Start_LipStick = 0x13C,
        Motion_Swing_4_LipStick = 0x13D,
        Motion_Swing_4_2_LipStick = 0x13E,
        Motion_Swing_4_Hold_LipStick = 0x13F,
        Motion_Swing_Dash_LipStick = 0x140,
        Motion_Item_Hammer_Wait = 0x141,
        Motion_Item_Hammer_Move = 0x142,
        Motion_Item_Hammer_Air = 0x143,
        Motion_Item_Hammer_Wait_ = 0x144,
        Motion_Item_Hammer_Move_ = 0x145,
        Motion_Item_Hammer_Air_ = 0x146,
        Motion_Item_Warpstar_Ride = 0x147,
        Motion_Item_Screw = 0x148,
        Motion_Item_Screw_Aerial = 0x149,
        Motion_Item_Screw_Fall = 0x14A,
        Motion_Guard_On_ = 0x14B,
        Motion_Item_Dragoon_Get  = 0x14C,
        Motion_Item_Dragoon_Ride = 0x14D,
        Motion_Item_Big = 0x14E,
        Motion_Item_Small = 0x14F,
        Motion_Item_Legs_Wait = 0x150,
        Motion_Item_Legs_Slow_F = 0x151,
        Motion_Item_Legs_Middle_F = 0x152,
        Motion_Item_Legs_Fast_F = 0x153,
        Motion_Item_Legs_Brake_F = 0x154,
        Motion_Item_Legs_Dash_F = 0x155,
        Motion_Item_Legs_Slow_B = 0x156,
        Motion_Item_Legs_Middle_B = 0x157,
        Motion_Item_Legs_Fast_B = 0x158,
        Motion_Item_Legs_Brake_B = 0x159,
        Motion_Item_Legs_Dash_B = 0x15A,
        Motion_Item_Legs_Jump_Squat = 0x15B,
        Motion_Item_Legs_Landing = 0x15C,
        Motion_Item_Shoot_Gun = 0x15D,
        Motion_Item_Shoot_Air_Gun = 0x15E,
        Motion_Item_Shoot_Gun_Empty = 0x15F,
        Motion_Item_Shoot_Air_Gun_Empty = 0x160,
        Motion_Item_Shoot_Flower = 0x161,
        Motion_Item_Shoot_Air_Flower = 0x162,
        Motion_Item_Scope_Start = 0x163,
        Motion_Item_Scope_Rapid = 0x164,
        Motion_Item_Scope_Fire = 0x165,
        Motion_Item_Scope_End = 0x166,
        Motion_Item_Scope_Air_Start = 0x167,
        Motion_Item_Scope_Air_Rapid = 0x168,
        Motion_Item_Scope_Air_Fire = 0x169,
        Motion_Item_Scope_Air_End = 0x16A,
        Motion_Item_Scope_Start_Empty = 0x16B,
        Motion_Item_Scope_Rapid_Empty = 0x16C,
        Motion_Item_Scope_Fire_Empty = 0x16D,
        Motion_Item_Scope_End_Empty = 0x16E,
        Motion_Item_Scope_Air_Start_Empty = 0x16F,
        Motion_Item_Scope_Air_Rapid_Empty = 0x170,
        Motion_Item_Scope_Air_Fire_Empty = 0x171,
        Motion_Item_Scope_Air_End_Empty = 0x172,
        Motion_Item_Launcher = 0x173,
        Motion_Item_Launcher_Fire = 0x174,
        Motion_Item_Launcher_Air_Fire = 0x175,
        Motion_Item_Launcher_Empty = 0x176,
        Motion_Item_Launcher_Fire_Empty = 0x177,
        Motion_Item_Launcher_Air_Fire_Empty = 0x178,
        Motion_Item_Launcher_Fall = 0x179,
        Motion_Item_Launcher_Air = 0x17A,
        Motion_Item_Assist = 0x17B,
        Motion_Gekikara_Wait = 0x17C,
        Motion_Barrel = 0x17D,
        Motion_Catapult = 0x17E,
        Motion_Ladder_Wait = 0x17F,
        Motion_Ladder_Up = 0x180,
        Motion_Ladder_Down = 0x181,
        Motion_Ladder_Catch_R = 0x182,
        Motion_Ladder_Catch_L = 0x183,
        Motion_Ladder_Catch_Air_R = 0x184,
        Motion_Ladder_Catch_Air_L = 0x185,
        Motion_Ladder_Catch_End_R = 0x186,
        Motion_Ladder_Catch_End_L = 0x187,
        Motion_Rope_Catch = 0x188,
        Motion_Rope_Fishing = 0x189,
        Motion_Special_N_Bitten_Start = 0x18A,
        Motion_Special_N_Bitten = 0x18B,
        Motion_Special_N_Bitten_End = 0x18C,
        Motion_Special_Air_N_Bitten_Start = 0x18D,
        Motion_Special_Air_N_Bitten = 0x18E,
        Motion_Special_Air_N_Bitten_End = 0x18F,
        Motion_Special_N_Dx_Bitten_Start = 0x190,
        Motion_Special_N_Dx_Bitten = 0x191,
        Motion_Special_N_Dx_Bitten_End = 0x192,
        Motion_Special_Air_N_Dx_Bitten_Start = 0x193,
        Motion_Special_Air_N_Dx_Bitten = 0x194,
        Motion_Special_Air_N_Dx_Bitten_End = 0x195,
        Motion_Special_N_Big_Bitten_Start = 0x196,
        Motion_Special_N_Big_Bitten = 0x197,
        Motion_Special_N_Big_Bitten_End = 0x198,
        Motion_Special_Air_N_Big_Bitten_Start = 0x199,
        Motion_Special_AIr_N_Big_Bitten = 0x19A,
        Motion_Special_Air_N_Big_Bitten_End = 0x19B,
        Motion_Special_Hi_Capture = 0x19C,
        Motion_Special_Hi_Dx_Capture = 0x19D,
        Motion_Special_S_Stick_Capture = 0x19E,
        Motion_Special_S_Stick_Attack_Capture = 0x19F,
        Motion_Special_S_Stick_Jump_Capture = 0x1A0,
        Motion_Special_S_Dx_Stick_Capture = 0x1A1,
        Motion_Special_S_Dx_Stick_Attack_Capture = 0x1A2,
        Motion_Special_S_Dx_Stick_Jump_Capture = 0x1A3,
        Motion_Thrown_Zitabata = 0x1A4,
        Motion_Thrown_Dx_Zitabata = 0x1A5,
        Motion_Thrown_Girl_Zitabata = 0x1A6,
        Motion_Thrown_F_F = 0x1A7,
        Motion_Thrown_F_B = 0x1A8,
        Motion_Thrown_F_Hi = 0x1A9,
        Motion_Thrown_F_Lw = 0x1AA,
        Motion_Thrown_Dx_F_F = 0x1AB,
        Motion_Thrown_Dx_F_B = 0x1AC,
        Motion_Thrown_Dx_F_Hi = 0x1AD,
        Motion_Thrown_Dx_F_Lw = 0x1AE,
        Motion_Ganon_Special_Hi_Capture = 0x1AF,
        Motion_Ganon_Special_Hi_Dx_Capture = 0x1B0,
        Motion_Special_S_Capture = 0x1B1,
        Motion_Special_Air_S_Catch_Capture = 0x1B2,
        Motion_Special_Air_S_Fall_Capture = 0x1B3,
        Motion_Special_Air_S_Capture = 0x1B4,
        Motion_Special_S_Dx_Capture = 0x1B5,
        Motion_Special_Air_S_Dx_Catch_Capture = 0x1B6,
        Motion_Special_Air_S_Dx_Fall_Capture = 0x1B7,
        Motion_Special_Air_S_Dx_Capture = 0x1B8,
        Motion_Special_N_Egg = 0x1B9,
        Motion_Special_S_Zitabata = 0x1BA,
        Motion_Special_S_Dx_Zitabata = 0x1BB,
        Motion_Appeal_Hi_R = 0x1BC,
        Motion_Appeal_Hi_L = 0x1BD,
        Motion_Appeal_S_R = 0x1BE,
        Motion_Appeal_S_L = 0x1BF,
        Motion_Appeal_Lw_R = 0x1C0,
        Motion_Appeal_Lw_L = 0x1C1,
        Motion_Entry_R = 0x1C2,
        Motion_Entry_L = 0x1C3,
        Motion_Win_1 = 0x1C4,
        Motion_Win_1_Wait = 0x1C5,
        Motion_Win_2 = 0x1C6,
        Motion_Win_2_Wait = 0x1C7,
        Motion_Win_3 = 0x1C8,
        Motion_Win_3_Wait = 0x1C9,
        Motion_Lose = 0x1CA,
        Motion_Damage_Face = 0x1CB,
        Motion_Dark = 0x1CC,
        Motion_Spycloak = 0x1CD,
    };

    enum TransitionTermId {
        Status_Transition_Term_Wait = 10000,
        Status_Transition_Term_Wait_From_Run_Brake = 10001,
        Status_Transition_Term_Fall = 10002,
        Status_Transition_Term_Fall_Aerial = 10003,
        Status_Transition_Term_Fall_Special = 10004,
        Status_Transition_Term_Damage_Fall = 10005,
        Status_Transition_Term_Damage_Fly_Reflect_L = 10006, // TODO: Verify
        Status_Transition_Term_Damage_Fly_Reflect_R = 10007, // TODO: Verify
        Status_Transition_Term_Damage_Fly_Reflect_U = 10008, // TODO: Verify
        Status_Transition_Term_Dash_To_Run = 10009,
        Status_Transition_Term_Slip = 10010,
        Status_Transition_Term_Run = 10011,
        Status_Transition_Term_Down = 10012,
        Status_Transition_Term_Down_Wait = 10013,
        Status_Transition_Term_Down_Stand = 10014,
        Status_Transition_Term_Down_Damage_Fall = 10015,
        Status_Transition_Term_Down_Damage_Reflect_L = 10016,
        Status_Transition_Term_Down_Damage_Reflect_R = 10017,
        Status_Transition_Term_Passive = 10018,
        Status_Transition_Term_Passive_Fb = 10019,
        Status_Transition_Term_Passive_Wall = 10020,
        Status_Transition_Term_Passive_Wall_Jump = 10021,
        Status_Transition_Term_Passive_Wall_Jump_Button = 10022,
        Status_Transition_Term_Passive_Ceil = 10023,
        Status_Transition_Term_Stop_Wall = 10024,
        Status_Transition_Term_Stop_Ceil = 10025,
        Status_Transition_Term_Landing = 10026,
        Status_Transition_Term_Landing_Light = 10027,
        Status_Transition_Term_Landing_Attack_Air = 10028,
        Status_Transition_Term_Landing_Fall_Special = 10029,
        Status_Transition_Term_Cliff_Catch = 10030,
        Status_Transition_Term_Glide = 10031,
        Status_Transition_Term_Glide_Landing = 10032,
        Status_Transition_Term_Squat_Wait = 10033,
        Status_Transition_Term_Catch_Wait = 10034,
        Status_Transition_Term_Capture_Wait = 10035,
        Status_Transition_Term_Capture_Cut = 10036,
        Status_Transition_Term_Cont_Escape = 10037,
        Status_Transition_Term_Cont_Escape_F = 10038,
        Status_Transition_Term_Cont_Escape_B = 10039,
        Status_Transition_Term_Cont_Guard_On = 10040,
        Status_Transition_Term_Cont_Guard = 10041,
        Status_Transition_Term_Cont_Jump_Squat = 10042,
        Status_Transition_Term_Cont_Jump_Squat_Button = 10043,
        Status_Transition_Term_Cont_Dash = 10044,
        Status_Transition_Term_Cont_Run_Brake = 10045,
        Status_Transition_Term_Cont_Turn = 10046,
        Status_Transition_Term_Cont_Turn_Run = 10047,
        Status_Transition_Term_Cont_Turn_Dash = 10048,
        Status_Transition_Term_Cont_Turn_Dash_Dash = 10049,
        Status_Transition_Term_Cont_Slip_Turn = 10050,
        Status_Transition_Term_Cont_Squat = 10051,
        Status_Transition_Term_Cont_Squat_Rv = 10052,
        Status_Transition_Term_Cont_Squat_Wait = 10053,
        Status_Transition_Term_Cont_Squat_F = 10054,
        Status_Transition_Term_Cont_Squat_B = 10055,
        Status_Transition_Term_Cont_Appeal_Hi = 10056,
        Status_Transition_Term_Cont_Appeal_S = 10057,
        Status_Transition_Term_Cont_Appeal_Lw = 10058,
        Status_Transition_Term_Cont_Walk = 10059,
        Status_Transition_Term_Cont_Escape_Air = 10060,
        Status_Transition_Term_Cont_Jump_Aerial = 10061,
        Status_Transition_Term_Cont_Jump_Aerial_Button = 10062,
        Status_Transition_Term_Cont_Tread_Jump = 10063,
        Status_Transition_Term_Cont_Tread_Jump_Button = 10064,
        Status_Transition_Term_Cont_Tread_Jump_No_Trigger = 10065,
        Status_Transition_Term_Cont_Fly = 10066,
        Status_Transition_Term_Cont_Fly_Button = 10067,
        Status_Transition_Term_Cont_Fly_Next = 10068,
        Status_Transition_Term_Cont_Cliff_Attack = 10069,
        Status_Transition_Term_Cont_Cliff_Special = 10070,
        Status_Transition_Term_Cont_Cliff_Escape = 10071,
        Status_Transition_Term_Cont_Cliff_Climb = 10072,
        Status_Transition_Term_Cont_Cliff_Fall = 10073,
        Status_Transition_Term_Cont_Cliff_Jump = 10074,
        Status_Transition_Term_Cont_Cliff_Jump_Button = 10075,
        Status_Transition_Term_Cont_Glide_Start = 10076,
        Status_Transition_Term_Cont_Glide_End = 10077,
        Status_Transition_Term_Cont_Glide_Attack = 10078,
        Status_Transition_Term_Cont_Pass = 10079,
        Status_Transition_Term_Cont_Air_Lasso = 10080,
        Status_Transition_Term_Cont_Attack = 10081,
        Status_Transition_Term_Cont_Attack_100 = 10082,
        Status_Transition_Term_Cont_Attack_Dash = 10083,
        Status_Transition_Term_Cont_Attack_S3 = 10084,
        Status_Transition_Term_Cont_Attack_Hi3 = 10085,
        Status_Transition_Term_Cont_Attack_Lw3 = 10086,
        Status_Transition_Term_Cont_Attack_S4 = 10087,
        Status_Transition_Term_Cont_Attack_S4_Start = 10088,
        Status_Transition_Term_Cont_Attack_S4_Hold = 10089,
        Status_Transition_Term_Cont_Attack_Hi4 = 10090,
        Status_Transition_Term_Cont_Attack_Hi4_Start = 10091,
        Status_Transition_Term_Cont_Attack_Hi4_Hold = 10092,
        Status_Transition_Term_Cont_Attack_Lw4 = 10093,
        Status_Transition_Term_Cont_Attack_Lw4_Start = 10094,
        Status_Transition_Term_Cont_Attack_Lw4_Hold = 10095,
        Status_Transition_Term_Cont_Attack_Air = 10096,
        Status_Transition_Term_Cont_Special_N = 10097,
        Status_Transition_Term_Cont_Special_S = 10098,
        Status_Transition_Term_Cont_Special_Hi = 10099,
        Status_Transition_Term_Cont_Special_Lw = 10100,
        Status_Transition_Term_Cont_Throw_Fb = 10101,
        Status_Transition_Term_Cont_Throw_Hi = 10102,
        Status_Transition_Term_Cont_Throw_Lw = 10103,
        Status_Transition_Term_Cont_Catch = 10104,
        Status_Transition_Term_Cont_Catch_Dash = 10105,
        Status_Transition_Term_Cont_Catch_Turn = 10106,
        Status_Transition_Term_Cont_Capture_Jump_Button = 10107,
        Status_Transition_Term_Cont_Capture_Jump = 10108,
        Status_Transition_Term_Cont_Item_Pickup_Light = 10109,
        Status_Transition_Term_Cont_Item_Pickup_Heavy = 10110,
        Status_Transition_Term_Cont_Item_Throw = 10111,
        Status_Transition_Term_Cont_Item_Throw_Guard = 10112,
        Status_Transition_Term_Cont_Item_Throw_Force = 10113,
        Status_Transition_Term_Cont_Item_Throw_Force_Dash = 10114,
        Status_Transition_Term_Cont_Item_Throw_Dash = 10115,
        Status_Transition_Term_Cont_Item_Throw_Dash_Clacker = 10116,
        Status_Transition_Term_Cont_Item_Swing_Bat_4 = 10117,
        Status_Transition_Term_Cont_Item_Swing_4 = 10118,
        Status_Transition_Term_Cont_Item_Swing_4_Hold = 10119,
        Status_Transition_Term_Cont_Item_Swing_3 = 10120,
        Status_Transition_Term_Cont_Item_Swing = 10121,
        Status_Transition_Term_Cont_Item_Swing_Dash = 10122,
        Status_Transition_Term_Cont_Item_Shoot = 10123,
        Status_Transition_Term_Cont_Item_Shoot_S3 = 10124,
        Status_Transition_Term_Cont_Item_Shoot_S4 = 10125,
        Status_Transition_Term_Cont_Item_Shoot_Wait = 10126,
        Status_Transition_Term_Cont_Item_Shoot_Walk_F = 10127,
        Status_Transition_Term_Cont_Item_Shoot_Walk_F_Brake = 10128,
        Status_Transition_Term_Cont_Item_Shoot_Walk_B = 10129,
        Status_Transition_Term_Cont_Item_Shoot_Walk_B_Brake = 10130,
        Status_Transition_Term_Cont_Item_Shoot_Dash_F = 10131,
        Status_Transition_Term_Cont_Item_Shoot_Dash_B = 10132,
        Status_Transition_Term_Cont_Item_Shoot_Air = 10133,
        Status_Transition_Term_Cont_Item_Shoot_Air_Pass = 10134,
        Status_Transition_Term_Cont_Item_Shoot_Jump_Button = 10135,
        Status_Transition_Term_Cont_Item_Shoot_Jump = 10136,
        Status_Transition_Term_Cont_Item_Shoot_Turn_Dash = 10137,
        Status_Transition_Term_Cont_Item_Shoot_Landing = 10138,
        Status_Transition_Term_Item_Gekikara_Wait = 10139,
        Status_Transition_Term_Item_Gekikara_Run = 10140,
        Status_Transition_Term_Cont_Item_Gekikara_Run_Brake = 10141,
        Status_Transition_Term_Throw_Kirby_Ground = 10142,
        Status_Transition_Term_Final = 10143,
        Status_Transition_Term_Throw_Enemy = 10144,
        Status_Transition_Term_Smash_Appeal = 10145, // TODO: Verify
    };

    enum TransitionTermGroupId {
        // 0x0
        Status_Transition_Term_Group_Chk_Ground_Special = 0x1,
        Status_Transition_Term_Group_Chk_Ground_Item = 0x2,
        Status_Transition_Term_Group_Chk_Ground_Catch = 0x3,
        Status_Transition_Term_Group_Chk_Ground_Attack = 0x4,
        Status_Transition_Term_Group_Chk_Ground_Escape = 0x5,
        Status_Transition_Term_Group_Chk_Ground_Guard = 0x6,
        Status_Transition_Term_Group_Chk_Ground_Jump = 0x7,
        Status_Transition_Term_Group_Chk_Ground = 0x8,
        Status_Transition_Term_Group_Chk_Air_Landing = 0x9,
        Status_Transition_Term_Group_Chk_Air_Cliff = 0xA,
        Status_Transition_Term_Group_Chk_Air_Special = 0xB,
        Status_Transition_Term_Group_Chk_Air_Item_Throw = 0xC,
        Status_Transition_Term_Group_Chk_Air_Lasso = 0xD,
        Status_Transition_Term_Group_Chk_Air_Escape = 0xE,
        Status_Transition_Term_Group_Chk_Air_Attack = 0xF,
        Status_Transition_Term_Group_Chk_Air_Tread_Jump = 0x10,
        Status_Transition_Term_Group_Chk_Air_Wall_Jump = 0x11,
        Status_Transition_Term_Group_Chk_Air_Jump_Aerial = 0x12,
        // 0x13
    };

    enum WorkId {
        Instance_Work_Int_Entry_Id = 0x10000000,
        Instance_Work_Int_Jump_Count = 0x10000001,
        Instance_Work_Int_Cliff_No_Catch_Frame = 0x10000002,
        Instance_Work_Int_Wall_Jump_Count = 0x10000003,
        Instance_Work_Int_Wall_Jump_Past_Frame = 0x10000004,
        Instance_Work_Int_Tread_Jump_Count = 0x10000005,
        Instance_Work_Int_No_Tread_Frame = 0x10000006,
        Instance_Work_Int_Tread_Target_Id = 0x10000007,
        Instance_Work_Int_Tread_Target_Category = 0x10000008,
        Instance_Work_Int_No_Slip_Frame = 0x10000009,
        Instance_Work_Int_No_Damage_Slip_Frame = 0x1000000A,
        Instance_Work_Int_No_Attach_Wall_Frame = 0x1000000B,
        Instance_Work_Int_Attach_Wall_Count = 0x1000000C,
        Instance_Work_Int_Speed_Y_Stable_Frame = 0x1000000D,
        Instance_Work_Int_No_Barrel_Frame = 0x1000000E,
        Instance_Work_Int_No_Catapult_Frame = 0x1000000F,
        Instance_Work_Int_No_Ground_Damage_Frame = 0x10000010,
        Instance_Work_Int_No_Ladder_Frame = 0x10000011,
        Instance_Work_Int_No_Spring_Frame = 0x10000012,
        Instance_Work_Int_Water_Jump_Count = 0x10000013,
        Instance_Work_Int_Water_Into_Frame = 0x10000014,
        Instance_Work_Int_Gimmick_Id = 0x10000015,
        Instance_Work_Int_Gimmick_Event_Manage_Id = 0x10000016,
        Instance_Work_Int_Gimmick_Kind = 0x10000017,
        Instance_Work_Int_Flower_Counter = 0x10000018,
        Instance_Work_Int_Gekikara_Counter = 0x10000019,
        Instance_Work_Int_Gekikara_Shoot_Counter = 0x1000001A,
        Instance_Work_Int_Hammer_Counter = 0x1000001B,
        Instance_Work_Int_Hammer_Throw_Counter = 0x1000001C,
        Instance_Work_Int_Hammer_SE_Handle = 0x1000001D,
        Instance_Work_Int_SuperStar_Counter = 0x1000001E,
        Instance_Work_Int_SuperStar_SE_Handle = 0x1000001F,
        Instance_Work_Int_Cursor_Frame = 0x10000020,
        Instance_Work_Int_Kinoko_Frame = 0x10000021,
        Instance_Work_Int_Thunder_Frame = 0x10000022,
        Instance_Work_Int_Scaling_Status = 0x10000023,
        Instance_Work_Int_Scaling_Kind = 0x10000024,
        Instance_Work_Int_Metal_Frame = 0x10000025,
        Instance_Work_Int_No_Heal_Frame = 0x10000026,
        Instance_Work_Int_No_Water_InOut_Frame = 0x10000027,
        Instance_Work_Int_Dead_Reason = 0x10000028,
        Instance_Work_Int_Dead_Mode = 0x10000029,
        Instance_Work_Int_Dead_Rebirth_Wait_Frame = 0x1000002A,
        Instance_Work_Int_Auto_Heal_Count = 0x1000002B, // TODO: Verify
        Instance_Work_Int_Succeed_Hit_Count = 0x1000002C,
        Instance_Work_Int_Loupe_Frame = 0x1000002D,
        Instance_Work_Int_Curry_SE_Handle = 0x1000002E,
        Instance_Work_Int_Heart_Swap_Target_Entry_Id = 0x1000002F,
        Instance_Work_Int_Heart_Swap_Item_Id = 0x10000030,
        Instance_Work_Int_No_Final_Frame = 0x10000031, // TODO: Verify
        Instance_Work_Int_Heal_Eff_Id = 0x10000032,
        Instance_Work_Int_Catch_Motion_Offset = 0x10000033, // TODO: Verify
        Instance_Work_Int_Thrown_Motion_Offset = 0x10000034, // TODO: Verify
        Instance_Work_Int_Attack_Serial_Id = 0x10000035,
        Instance_Work_Int_Color = 0x10000036,
        Instance_Work_Int_Status_Start_Turn_Frame = 0x10000037,
        Instance_Work_Int_Damage_Reaction_Frame = 0x10000038,
        Instance_Work_Int_Meteor_Counter_Frame = 0x10000039,
        Instance_Work_Int_Badge_Stop_Frame = 0x1000003A, // TODO: Verify
        Instance_Work_Int_Screw_Jump_Count = 0x1000003B,
        Instance_Work_Int_No_Pickup_Item_Frame = 0x1000003C, // TODO: Verify
        Instance_Work_Int_Fly_Reflect_Count = 0x1000003D,
        Instance_Work_Int_Air_Lasso_Count = 0x1000003E,
        Instance_Work_Int_Damage_Entry_Id = 0x1000003F,


        Instance_Work_Float_Landing_Frame = 0x11000000,
        Instance_Work_Float_Fall_X_Accel_Mul = 0x11000001,
        Instance_Work_Float_Wall_Jump_Dir = 0x11000002,
        Instance_Work_Float_Guard_Shield = 0x11000003,
        Instance_Work_Float_Guard_Shield_Min = 0x11000004, // TODO: Verify
        Instance_Work_Float_Guard_Shield_Max = 0x11000005, // TODO: Verify
        Instance_Work_Float_Flower_Total_Damage = 0x11000006,
        Instance_Work_Float_Gekikara_Angle = 0x11000007,
        Instance_Work_Float_Gekikara_Angle_Speed = 0x11000008,
        Instance_Work_Float_Scaling_Start_Scale = 0x11000009,
        Instance_Work_Float_Scaling_End_Scale = 0x1100000A,
        Instance_Work_Float_Scaling_Init_Scale = 0x1100000B,
        Instance_Work_Float_Metal_Power = 0x1100000C,
        Instance_Work_Float_Succeed_Hit_Damage = 0x1100000D,
        Instance_Work_Float_Reaction_Cheer = 0x1100000E,
        Instance_Work_Float_Damage_Speed_Reserved_X = 0x1100000F,   // TODO: Verify (set in ftKineticTransactor::changeKinetic)
        Instance_Work_Float_Damage_Speed_Reserved_Y = 0x11000010,   // TODO: Verify
        Instance_Work_Float_Init_Pitch = 0x11000011,
        Instance_Work_Float_Cursor_Offset_Y = 0x11000012,


        Instance_Work_Flag_Dead_End = 0x12000000,
        Instance_Work_Flag_No_Dead = 0x12000001,
        Instance_Work_Flag_Catch_Cliff = 0x12000002,
        Instance_Work_Flag_Disable_Landing_Cancel = 0x12000003,
        Instance_Work_Flag_Disable_Landing_Turn = 0x12000004,
        Instance_Work_Flag_Tread_No_Trigger = 0x12000005,
        Instance_Work_Flag_Final = 0x12000006,
        Instance_Work_Flag_Final_Status = 0x12000007,
        Instance_Work_Flag_Final_Available = 0x12000008,
        Instance_Work_Flag_Flower = 0x12000009,
        Instance_Work_Flag_Gekikara = 0x1200000A,
        Instance_Work_Flag_Hammer = 0x1200000B,
        Instance_Work_Flag_Hammer_No_Attack = 0x1200000C,
        Instance_Work_Flag_Hammer_No_Drift = 0x1200000D,
        Instance_Work_Flag_Star = 0x1200000E,
        Instance_Work_Flag_Screw = 0x1200000F,
        Instance_Work_Flag_Pikmin_Final_No_Reaction = 0x12000010, // TODO: Verify
        Instance_Work_Flag_Paralyze_Damage = 0x12000011,
        Instance_Work_Flag_Metal = 0x12000012,
        Instance_Work_Flag_Rabbit_Cap = 0x12000013,
        Instance_Work_Flag_Kinoko = 0x12000014,
        Instance_Work_Flag_Thunder = 0x12000015,
        Instance_Work_Flag_No_Glide = 0x12000016, // TODO: Verify
        Instance_Work_Flag_Dead_Area_Out = 0x12000017,
        Instance_Work_Flag_KnockOut = 0x12000018,
        Instance_Work_Flag_Loupe = 0x12000019,
        Instance_Work_Flag_Loupe_Damage = 0x1200001A,
        Instance_Work_Flag_Cursor = 0x1200001B,
        Instance_Work_Flag_Name_Cursor = 0x1200001C,
        Instance_Work_Flag_Rebirth_No_Move = 0x1200001D,
        Instance_Work_Flag_Final_Discretion = 0x1200001E,
        Instance_Work_Flag_Kirby_Copy_Dedede = 0x1200001F,
        Instance_Work_Flag_Speed_Damage = 0x12000020,
        Instance_Work_Flag_Disable_Scaling = 0x12000021,
        Instance_Work_Flag_Disable_Cliff_Catch = 0x12000022,

        Instance_Work_Flag_Disable_Ottotto = 0x12000024,
        Instance_Work_Flag_Disable_Slip = 0x12000025,
        Instance_Work_Flag_Slow = 0x12000026,
        Instance_Work_Flag_Slow_Cause_Timer = 0x12000027,
        Instance_Work_Flag_No_Dead_Up = 0x12000028,
        Instance_Work_Flag_No_Dead_Down = 0x12000029,
        Instance_Work_Flag_Item_Throw_4 = 0x1200002A,
        Instance_Work_Flag_Assist = 0x1200002B,
        Instance_Work_Flag_Check_Catch = 0x1200002C,

        Instance_Work_Flag_Sub_Fighter = 0x1200002E, // TODO: Verify
        Instance_Work_Flag_No_Swim = 0x1200002F,
        Instance_Work_Flag_Disable_Curry_Shot = 0x12000030,
        Instance_Work_Flag_Disable_Interrupt_Swim = 0x12000031,
        Instance_Work_Flag_Disable_Interrupt_Scaling = 0x12000032,
        Instance_Work_Flag_Voice_Mute = 0x12000033,
        Instance_Work_Flag_Paralyze_Stop = 0x12000037,
        Instance_Work_Flag_Calc_Cursor_Pos_Force = 0x12000038,
        Instance_Work_Flag_No_Speed_Operation_Chk = 0x12000039, // TODO: Verify
        Instance_Work_Flag_Force_Loupe = 0x1200003A, // TODO: Verify
        Instance_Work_Flag_Capture_Yoshi = 0x1200003B,
        Instance_Work_Flag_Cursor_On_Posture = 0x1200003C,

        Status_Work_Float_Reserve_Hold_Rate = 0x21000000,
        Status_Work_Float_Rebound_Frame = 0x21000001,
        Status_Work_Float_Rebound_Lr = 0x21000002,


        Status_Work_Flag_Dive = 0x22000002,

        Status_Work_Flag_Jump_Mini = 0x22000006,
        Status_Work_Flag_Jump_From_Tread = 0x22000007,
        Status_Work_Flag_Jump_From_Ladder = 0x22000008,

        Status_Work_Flag_Jump_From_Shoot = 0x2200000A,
        Status_Work_Flag_Jump_From_Water = 0x2200000B,
        Status_Work_Flag_Jump_From_Spring = 0x2200000C,
        Status_Work_Flag_Disable_Outside_Energy = 0x2200000D,


        Status_Tread_Work_Float_Jump_Speed_Mul = 0x21000004,
        Status_Item_Throw_Work_Float_Lr = 0x21000004,
        Status_Gimmick_Spring_Work_Float_Shoot_Speed_Y = 0x21000004,
        Status_Gimmick_Spring_Work_Float_Shoot_Angle = 0x21000005,
    };

    enum DeadReason {
        Dead_Reason_Outside_Up = 0x0,
        Dead_Reason_Outside_Down = 0x1,
        Dead_Reason_Outside_Left = 0x2,
        Dead_Reason_Outside_Right = 0x3,
        Dead_Reason_Ground_Crush = 0x4,
        Dead_Reason_KnockOut = 0x5,
        Dead_Reason_Instant_Death = 0x6
    };

    enum DeadMode {
        Dead_Mode_Normal = 0x0,
        Dead_Mode_DeadUp_Star = 0x1,
        Dead_Mode_DeadUp_Fall = 0x2
    };

    enum ScalingStatus {
        Scaling_Status_None = 0x0,
        Scaling_Status_End_Small = 0x1,
        Scaling_Status_End_Big = 0x2,
        Scaling_Status_Big = 0x3,
        Scaling_Status_To_Big = 0x4,
        Scaling_Status_Small = 0x5,
        Scaling_Status_To_Small = 0x6,
    };

    enum ScalingKind {
        Scaling_Kind_None = -0x1,
        Scaling_Kind_Status = 0x0,
        Scaling_Kind_Kinoko = 0x1,
        Scaling_Kind_Thunder = 0x2,
    };

    enum ScalingType {
        Scaling_Type_None = -0x1,
        Scaling_Type_Big = 0x0,
        Scaling_Type_Small = 0x1,
    };

    enum KineticEnergyType {
        Kinetic_Energy_Motion = 0x0,
        Kinetic_Energy_Gravity = 0x1,
        Kinetic_Energy_Control = 0x2,
        Kinetic_Energy_Stop = 0x3,
        Kinetic_Energy_Damage = 0x4,
        Kinetic_Energy_Env_Wind = 0x5,
        Kinetic_Energy_Ground_Movement = 0x6,
        Kinetic_Energy_Jostle = 0x7,
    };

    enum AreaKind {
        Area_Body = 0x0,

        Area_Tread_Jump_Check = 0x2,

        Area_Item_Pickup = 0x6,
        Area_Item_Pickup_Air = 0x7,
        Area_Wind = 0x8
    };

    int m_entryId;
    char _272[44];
    ftOutsideEventPresenter m_outsideEventPresenter;
    char _332[72];

    virtual void processUpdate();
    virtual void processFixPosition();
    virtual void processHit();
    virtual void processFixCamera();
    virtual void processEnd();
    virtual ~Fighter();

    // TODO: Verify parameters
    virtual void postCreate();
    virtual Fighter* getPartner();
    virtual void attachInstance();
    virtual void detachInstance();
    virtual void standbyAdvFollow();
    virtual void onStartFinal(int variantID = -1, itCustomizerInterface** customizer = NULL); // Note: Optional parameters for modding purposes to use custom customizers
    virtual void onEndFinal();
    virtual void toDead(int);
    virtual int checkDead();
    virtual void onDeadEnd();
    virtual void toKnockOut();
    virtual void activate();
    virtual void onActivate();
    virtual void onDeactivate();
    virtual void onStart(int);
    virtual void postStart(int);
    virtual void setCursor(bool);
    virtual void setNameCursor(bool);
    virtual void setLoupe(bool);
    virtual void setLoupeDamage(bool);
    virtual u32 getChangeSucceedOption();
    virtual void changeSucceedCore(void*, int);
    virtual void setupChangeSucceedWork(void*);
    virtual bool setupChangeSucceedEffect();
    virtual void change(void*, int);
    virtual void touchItem(void*);
    virtual bool setMetal(bool setStatus, float health, int unk3);
    virtual void onSetMetal(bool);
    virtual void onHitReflector(soModuleAccesser* moduleAccesser, bool);
    virtual void dropItemCheck(void*, bool);
    virtual bool isHeartSwapEnableCondition();
    virtual void analyzeSeal(void*);
    virtual void notifyEventCollisionAttack(float power, soCollisionLog* collisionLog, soModuleAccesser* moduleAccesser);
    virtual bool notifyEventCollisionAttackFighter(void* unk, soModuleAccesser* moduleAccesser);
    virtual ftOwner* getOwner();
    virtual ftKind getFtKind();
    virtual bool isInclude(float* rect, Vec3f* out);
    virtual void eatItem(void*);
    virtual void notifyEventChangeStatus(int statusKind, int prevStatusKind, soStatusData* statusData, soModuleAccesser* moduleAccesser);
    virtual void notifyEventChangeSituation(SituationKind kind, SituationKind prevKind, soModuleAccesser* moduleAccesser);
    virtual bool notifyEventCollisionAttackCheck(u32 flags);
    virtual void notifyEventCollisionShield(soCollisionAttackModule* attackModule, soCollisionLog* collisionLog, u32 groupIndex, soModuleAccesser* moduleAccesser, float power, float posX, float);
    virtual void notifyEventCollisionShieldSearch(soCollisionSearchModule* searchModule, soCollisionLog* collisionLog, u32 groupIndex, soModuleAccesser* moduleAccesser);
    virtual bool notifyEventCollisionShieldCheck();
    virtual void notifyEventCollisionReflector(soCollisionAttackModule* attackModule, soCollisionLog* collisionLog, u32 groupIndex, soModuleAccesser* moduleAccesser, float power, float posX, float);
    virtual void notifyEventCollisionReflectorSearch(soCollisionSearchModule* searchModule, soCollisionLog* collisionLog, u32 groupIndex, soModuleAccesser* moduleAccesser);
    virtual bool notifyEventCollisionReflectorCheck();
    virtual void notifyEventCollisionAbsorber(soCollisionAttackModule* attackModule, soCollisionLog* collisionLog, u32 groupIndex, soModuleAccesser* moduleAccesser, float power, float posX, float);
    virtual bool notifyEventCollisionAbsorberCheck();
    virtual bool notifyEventCaptureStatus(soModuleAccesser* moduleAccesser, int taskId, int, int);
    virtual void notifyEventCollisionSearch(soCollisionLog* collisionLog, soModuleAccesser* moduleAccesser);
    virtual bool notifyEventCollisionSearchCheck();
    virtual void notifyEventChangeCollisionHit(int index, soModuleAccesser* moduleAccesser);
    virtual void notifyEventOnDamage(soDamage* damage, bool, soModuleAccesser* moduleAccesser);
    virtual void notifyEventAddDamage(soDamage* damage, soModuleAccesser* moduleAccesser);
    virtual void setTeam(int, int);
    virtual void setVisibility(int);
    virtual void notifyEventTurn(float, float, soModuleAccesser* moduleAccesser);
    virtual bool notifyHaveItemPreCheck(BaseItem* item, bool*);
    virtual void notifyHaveItem(itParam::SizeKind, BaseItem* item, u32 nodeIndex, u32 index, bool);
    virtual void notifyAttachItem(BaseItem* item, u32 nodeIndex, u32 attachNodeIndex, bool, bool);
    virtual void notifyUseItem(BaseItem* item, u32 nodeIndex, int*);
    virtual void notifyThrowItem(BaseItem* item, u32 nodeIndex, int*);
    virtual void notifyDropItem(BaseItem*);
    virtual void notifyShootBulletItem(BaseItem* item);
    virtual void notifyEjectItem(BaseItem* item, u32 index, bool);
    virtual void notifyEjectAttachItem(BaseItem* item, u32 index, bool);
    virtual void notifyVisibilityItem(BaseItem* item, int, bool, u8);
    virtual void notifyEventSetDamage(float);
    virtual void notifyEventChangeAdvUnit();
    virtual void notifyEventBeat();
    virtual void playEatSE();
    virtual void onInhaled();
    virtual bool isInhaled();
    virtual void offInhaled();
    virtual void notifyEventPikminFinalAttack(float, int);
    virtual void trainerStart(float, Vec3f*, Vec3f*, int, bool);
    virtual void trainerRestart(float*, bool, bool);
    virtual void disappear(bool);
    virtual bool isEnableCancel();
    virtual void* getCancelModule();
    virtual void* getStatusGimmickUniqProcessPool();
    virtual void* getVirtualNodeMatrixPool();

    void start(Vec3f* pos, float lr, float damage, int, bool);
    void setCurry(bool setStatus, int unk2);
    void setHammer(bool setStatus, int unk2);
    void setSuperStar(bool setStatus, int duration, bool);
    void setFlower(bool setStatus, float rate, float size, int unk4, bool unk5);
    void setSlow(bool setStatus, int slowStrength, int duration, bool useTimerEffect);
    void setHeartSwap(int givingPlayerEntryID, int givingPlayerEntryId, bool setStatus);
    void startScaling(ScalingKind, ScalingType);
    void warp(Vec3f* pos, float lr, u32 showEffect);
    void setupEquipment();
};
static_assert(sizeof(Fighter) == 404, "Class is wrong size!");