#pragma once

enum MuSelchkind { /* CSS */
    MuSelch_Mario=0,
    MuSelch_Donkey=1,
    MuSelch_Link=2,
    MuSelch_Samus=3,
    MuSelch_SZeroSuit=4,
    MuSelch_Yoshi=5,
    MuSelch_Kirby=6,
    MuSelch_Fox=7,
    MuSelch_Pikachu=8,
    MuSelch_Luigi=9,
    MuSelch_Captain=10,
    MuSelch_Ness=11,
    MuSelch_Koopa=12,
    MuSelch_Peach=13,
    MuSelch_Zelda=14,
    MuSelch_Sheik=15,
    MuSelch_Popo=16,
    MuSelch_Marth=17,
    MuSelch_GameWatch=18,
    MuSelch_Falco=19,
    MuSelch_Ganon=20,
    MuSelch_Wario=21,
    MuSelch_MetaKnight=22,
    MuSelch_Pit=23,
    MuSelch_Pikmin=24,
    MuSelch_Lucas=25,
    MuSelch_Diddy=26,
    MuSelch_PokeTrainer=27,
    MuSelch_PokeLizardon=28,
    MuSelch_PokeZenigame=29,
    MuSelch_PokeFushigisou=30,
    MuSelch_Dedede=31,
    MuSelch_Lucario=32,
    MuSelch_Ike=33,
    MuSelch_Robot=34,
    MuSelch_Purin=35,
    MuSelch_ToonLink=36,
    MuSelch_Wolf=37,
    MuSelch_Snake=38,
    MuSelch_Sonic=39,
    MuSelch_SelectNone=40,
    MuSelch_Random=41,
    MuSelch_Boss_BossPackun=45,
    MuSelch_Boss_Rayquaza=46,
    MuSelch_Boss_PorkyStatue=47,
    MuSelch_Boss_Porky=48,
    MuSelch_Boss_Galleom=49,
    MuSelch_Boss_Ridley=50,
    MuSelch_Boss_Duon=51,
    MuSelch_Boss_MetaRidley=52,
    MuSelch_Boss_Taboo=53,
    MuSelch_Boss_MasterHand=54,
    MuSelch_Boss_CrazyHand=55,
    MuSelch_Zako_Boy=56,
    MuSelch_Zako_Girl=57,
    MuSelch_Zako_Child=58,
    MuSelch_Zako_Ball=59
};

enum MuStockchkind { /* Cosmetic */
    MuStockch_Mario=0,
    MuStockch_Donkey=1,
    MuStockch_Link=2,
    MuStockch_Samus=3,
    MuStockch_Yoshi=4,
    MuStockch_Kirby=5,
    MuStockch_Fox=6,
    MuStockch_Pikachu=7,
    MuStockch_Luigi=8,
    MuStockch_Captain=9,
    MuStockch_Ness=10,
    MuStockch_Koopa=11,
    MuStockch_Peach=12,
    MuStockch_Zelda=13,
    MuStockch_Sheik=14,
    MuStockch_Popo=15,
    MuStockch_Marth=16,
    MuStockch_GameWatch=17,
    MuStockch_Falco=18,
    MuStockch_Ganon=19,
    MuStockch_Wario=20,
    MuStockch_MetaKnight=21,
    MuStockch_Pit=22,
    MuStockch_SZeroSuit=23,
    MuStockch_Pikmin=24,
    MuStockch_Lucas=25,
    MuStockch_Diddy=26,
    MuStockch_PokeTrainer=27,
    MuStockch_PokeLizardon=28,
    MuStockch_PokeZenigame=29,
    MuStockch_PokeFushigisou=30,
    MuStockch_Dedede=31,
    MuStockch_Lucario=32,
    MuStockch_Ike=33,
    MuStockch_Robot=34,
    MuStockch_Purin=35,
    MuStockch_ToonLink=37,
    MuStockch_ZeldaSheik=38,
    MuStockch_Wolf=39,
    MuStockch_Snake=40,
    MuStockch_Sonic=41,
    MuStockch_Random=42,
    MuStockch_Sandbag=43,
    MuStockch_Target=44,
    MuStockch_Boss_BossPackun=45,
    MuStockch_Boss_Rayquaza=46,
    MuStockch_Boss_PorkyStatue=47,
    MuStockch_Boss_Porky=48,
    MuStockch_Boss_Galleom=49,
    MuStockch_Boss_Ridley=50,
    MuStockch_Boss_Duon=51,
    MuStockch_Boss_MetaRidley=52,
    MuStockch_Boss_Taboo=53,
    MuStockch_Boss_MasterHand=54,
    MuStockch_Boss_CrazyHand=55,
    MuStockch_Zako_Boy=56,
    MuStockch_Zako_Girl=57,
    MuStockch_Zako_Child=58,
    MuStockch_Zako_Ball=59,
    MuStockch_Smash=60,
    MuStockch_SelectNone=61
};

enum MuCharKind { /* Record Bank */
    MuChar_Mario=0,
    MuChar_Donkey=1,
    MuChar_Link=2,
    MuChar_Samus=3,
    MuChar_Yoshi=4,
    MuChar_Kirby=5,
    MuChar_Fox=6,
    MuChar_Pikachu=7,
    MuChar_Luigi=8,
    MuChar_Captain=9,
    MuChar_Ness=10,
    MuChar_Koopa=11,
    MuChar_Peach=12,
    MuChar_Zelda=13,
    MuChar_Popo=14,
    MuChar_Falco=15,
    MuChar_Ganon=16,
    MuChar_Wario=17,
    MuChar_MetaKnight=18,
    MuChar_Pit=19,
    MuChar_Pikmin=20,
    MuChar_Lucas=21,
    MuChar_Diddy=22,
    MuChar_Dedede=23,
    MuChar_Ike=24,
    MuChar_Robot=25,
    MuChar_Snake=26,
    MuChar_PokeTrainer=27,
    MuChar_Lucario=28,
    MuChar_Marth=29,
    MuChar_GameWatch=30,
    MuChar_Purin=31,
    MuChar_ToonLink=32,
    MuChar_Wolf=33,
    MuChar_Sonic=34
};

enum MuStageKind {
    MuStage_Battle = 0,
    MuStage_Final = 1,
    MuStage_Dolpic = 2,
    MuStage_Mansion = 3,
    MuStage_MarioPast = 4,
    MuStage_Kart = 5,
    MuStage_Donkey = 6,
    MuStage_Jungle = 7,
    MuStage_Pirates = 8,
    MuStage_Oldin = 9,
    MuStage_Norfair = 10,
    MuStage_Orpheon = 11,
    MuStage_Crayon = 12,
    MuStage_Halberd = 13,
    MuStage_StarFox = 14,
    MuStage_Stadium = 15,
    MuStage_Tengan = 16,
    MuStage_FZero = 17,
    MuStage_Ice = 18,
    MuStage_GW = 19,
    MuStage_Emblem = 20,
    MuStage_Madein = 21,
    MuStage_Earth = 22,
    MuStage_Palutena = 23,
    MuStage_Famicom = 24,
    MuStage_NewPork = 25,
    MuStage_Village = 26,
    MuStage_MetalGear = 27,
    MuStage_GreenHill = 28,
    MuStage_PictChat = 29,
    MuStage_Plankton = 30,
    MuStage_DxShrine = 31,
    MuStage_DxYorster = 32,
    MuStage_DxGarden = 33,
    MuStage_DxOnett = 34,
    MuStage_DxGreens = 35,
    MuStage_DxCruise = 36,
    MuStage_DxCorneria = 37,
    MuStage_DxBigBlue = 38,
    MuStage_DxZebes = 39,
    MuStage_DxPStadium = 40,
    MuStage_Edit = 41
};

namespace muMenu {
    //    int activeRumbleController;
    //    int globalRumbleSetting;

    static void loadMenuSound();
    static bool isLoadFinishMenuSound();
    static int exchangeSelchkind2SelCharVoice(int id);
    static int exchangeSelCharVoice2SelCharVoiceLengthE(int id);
    static int exchangeSelCharVoice2SelCharVoiceLengthJ(int id);
    static int exchangeGmCharacterKind2MuStockchkind(int id);
    static int exchangeGmCharacterKind2Something(int id);
    static void startRumbleController(int controller, int rumbleStrength, int rumbleSetting);
    static int exchangeMuSelchkind2MuStockchkind(int id);
    static const char* exchangeMuStockchkind2MuCharName(int id);
    static int getStockFrameID(int id);
};
