#pragma once

enum MuSelchkind { /* CSS */
    MuSelchkind_Mario=0,
    MuSelchkind_Donkey=1,
    MuSelchkind_Link=2,
    MuSelchkind_Samus=3,
    MuSelchkind_SZeroSuit=4,
    MuSelchkind_Yoshi=5,
    MuSelchkind_Kirby=6,
    MuSelchkind_Fox=7,
    MuSelchkind_Pikachu=8,
    MuSelchkind_Luigi=9,
    MuSelchkind_Captain=10,
    MuSelchkind_Ness=11,
    MuSelchkind_Koopa=12,
    MuSelchkind_Peach=13,
    MuSelchkind_Zelda=14,
    MuSelchkind_Sheik=15,
    MuSelchkind_Popo=16,
    MuSelchkind_Marth=17,
    MuSelchkind_GameWatch=18,
    MuSelchkind_Falco=19,
    MuSelchkind_Ganon=20,
    MuSelchkind_Wario=21,
    MuSelchkind_MetaKnight=22,
    MuSelchkind_Pit=23,
    MuSelchkind_Pikmin=24,
    MuSelchkind_Lucas=25,
    MuSelchkind_Diddy=26,
    MuSelchkind_PokeTrainer=27,
    MuSelchkind_PokeLizardon=28,
    MuSelchkind_PokeZenigame=29,
    MuSelchkind_PokeFushigisou=30,
    MuSelchkind_Dedede=31,
    MuSelchkind_Lucario=32,
    MuSelchkind_Ike=33,
    MuSelchkind_Robot=34,
    MuSelchkind_Purin=35,
    MuSelchkind_ToonLink=36,
    MuSelchkind_Wolf=37,
    MuSelchkind_Snake=38,
    MuSelchkind_Sonic=39,
    MuSelchkind_SelectNone=40,
    MuSelchkind_Random=41,
    MuSelchkind_Boss_BossPackun=45,
    MuSelchkind_Boss_Rayquaza=46,
    MuSelchkind_Boss_PorkyStatue=47,
    MuSelchkind_Boss_Porky=48,
    MuSelchkind_Boss_Galleom=49,
    MuSelchkind_Boss_Ridley=50,
    MuSelchkind_Boss_Duon=51,
    MuSelchkind_Boss_MetaRidley=52,
    MuSelchkind_Boss_Taboo=53,
    MuSelchkind_Boss_MasterHand=54,
    MuSelchkind_Boss_CrazyHand=55,
    MuSelchkind_Zako_Boy=56,
    MuSelchkind_Zako_Girl=57,
    MuSelchkind_Zako_Child=58,
    MuSelchkind_Zako_Ball=59
};

enum MuStockchkind { /* Cosmetic */
    MuStockchkind_Mario=0,
    MuStockchkind_Donkey=1,
    MuStockchkind_Link=2,
    MuStockchkind_Samus=3,
    MuStockchkind_Yoshi=4,
    MuStockchkind_Kirby=5,
    MuStockchkind_Fox=6,
    MuStockchkind_Pikachu=7,
    MuStockchkind_Luigi=8,
    MuStockchkind_Captain=9,
    MuStockchkind_Ness=10,
    MuStockchkind_Koopa=11,
    MuStockchkind_Peach=12,
    MuStockchkind_Zelda=13,
    MuStockchkind_Sheik=14,
    MuStockchkind_Popo=15,
    MuStockchkind_Marth=16,
    MuStockchkind_GameWatch=17,
    MuStockchkind_Falco=18,
    MuStockchkind_Ganon=19,
    MuStockchkind_Wario=20,
    MuStockchkind_MetaKnight=21,
    MuStockchkind_Pit=22,
    MuStockchkind_SZeroSuit=23,
    MuStockchkind_Pikmin=24,
    MuStockchkind_Lucas=25,
    MuStockchkind_Diddy=26,
    MuStockchkind_PokeTrainer=27,
    MuStockchkind_PokeLizardon=28,
    MuStockchkind_PokeZenigame=29,
    MuStockchkind_PokeFushigisou=30,
    MuStockchkind_Dedede=31,
    MuStockchkind_Lucario=32,
    MuStockchkind_Ike=33,
    MuStockchkind_Robot=34,
    MuStockchkind_Purin=35,
    MuStockchkind_ToonLink=37,
    MuStockchkind_ZeldaSheik=38,
    MuStockchkind_Wolf=39,
    MuStockchkind_Snake=40,
    MuStockchkind_Sonic=41,
    MuStockchkind_Random=42,
    MuStockchkind_Sandbag=43,
    MuStockchkind_Target=44,
    MuStockchkind_Boss_BossPackun=45,
    MuStockchkind_Boss_Rayquaza=46,
    MuStockchkind_Boss_PorkyStatue=47,
    MuStockchkind_Boss_Porky=48,
    MuStockchkind_Boss_Galleom=49,
    MuStockchkind_Boss_Ridley=50,
    MuStockchkind_Boss_Duon=51,
    MuStockchkind_Boss_MetaRidley=52,
    MuStockchkind_Boss_Taboo=53,
    MuStockchkind_Boss_MasterHand=54,
    MuStockchkind_Boss_CrazyHand=55,
    MuStockchkind_Zako_Boy=56,
    MuStockchkind_Zako_Girl=57,
    MuStockchkind_Zako_Child=58,
    MuStockchkind_Zako_Ball=59,
    MuStockchkind_Smash=60,
    MuStockchkind_SelectNone=61
};

enum MuCharKind { /* Record Bank */
    MuCharKind_Mario=0,
    MuCharKind_Donkey=1,
    MuCharKind_Link=2,
    MuCharKind_Samus=3,
    MuCharKind_Yoshi=4,
    MuCharKind_Kirby=5,
    MuCharKind_Fox=6,
    MuCharKind_Pikachu=7,
    MuCharKind_Luigi=8,
    MuCharKind_Captain=9,
    MuCharKind_Ness=10,
    MuCharKind_Koopa=11,
    MuCharKind_Peach=12,
    MuCharKind_Zelda=13,
    MuCharKind_Popo=14,
    MuCharKind_Falco=15,
    MuCharKind_Ganon=16,
    MuCharKind_Wario=17,
    MuCharKind_MetaKnight=18,
    MuCharKind_Pit=19,
    MuCharKind_Pikmin=20,
    MuCharKind_Lucas=21,
    MuCharKind_Diddy=22,
    MuCharKind_Dedede=23,
    MuCharKind_Ike=24,
    MuCharKind_Robot=25,
    MuCharKind_Snake=26,
    MuCharKind_PokeTrainer=27,
    MuCharKind_Lucario=28,
    MuCharKind_Marth=29,
    MuCharKind_GameWatch=30,
    MuCharKind_Purin=31,
    MuCharKind_ToonLink=32,
    MuCharKind_Wolf=33,
    MuCharKind_Sonic=34
};

class muMenu {
public:
    //    int activeRumbleController;
    //    int globalRumbleSetting;

    static void loadMenuSound();
    static bool isLoadFinishMenuSound();
    static int exchangeSelchkind2SelCharVoice(int id);
    static int exchangeSelCharVoice2SelCharVoiceLengthE(int id);
    static int exchangeSelCharVoice2SelCharVoiceLengthJ(int id);
    static int exchangeGmCharacterKind2MuStockchkind(int id);
    static int exchangeGmCharacterKind2Something(int id);
    static void startRumbleController(int controller, int rumbleStrength, int rumbleSetting);
    static int exchangeMuSelchkind2MuStockchkind(int id);
    static char* exchangeMuStockchkind2MuCharName(int id);
    static int getStockFrameID(int id);
};
