#pragma once

namespace Stages {
    enum StageKind {
        Stage_battle = 0x01,
        Stage_final = 0x02,
        Stage_dolpic = 0x03,
        Stage_mansion = 0x04,
        Stage_mariopast = 0x05,
        Stage_kart = 0x06,
        Stage_donkey = 0x07,
        Stage_jungle = 0x08,
        Stage_pirates = 0x09,
        Stage_norfair = 0x0B,
        Stage_orpheon = 0x0C,
        Stage_crayon = 0x0D,
        Stage_halberd = 0x0E,
        Stage_starfox = 0x13,
        Stage_stadium = 0x14,
        Stage_tengan = 0x15,
        Stage_fzero = 0x16,
        Stage_ice = 0x17,
        Stage_gw = 0x18,
        Stage_emblem = 0x19,
        Stage_madein = 0x1C,
        Stage_earth = 0x1D,
        Stage_palutena = 0x1E,
        Stage_famicom = 0x1F,
        Stage_newpork = 0x20,
        Stage_village = 0x21,
        Stage_metalgear = 0x22,
        Stage_greenhill = 0x23,
        Stage_pictchat = 0x24,
        Stage_plankton = 0x25,
        Stage_config = 0x26,
        Stage_dxshrine = 0x29,
        Stage_dxyorster = 0x2A,
        Stage_dxgarden = 0x2B,
        Stage_dxonett = 0x2C,
        Stage_dxgreens = 0x2D,
        Stage_dxpstadium = 0x2E,
        Stage_dxrcruise = 0x2F,
        Stage_dxcorneria = 0x30,
        Stage_dxbigblue = 0x31,
        Stage_dxzebes = 0x32,
        Stage_oldin = 0x33,
        Stage_homerun = 0x34,
        Stage_stageedit = 0x35,
        Stage_heal = 0x36,
        Stage_otrain = 0x37,
        Stage_tbreak = 0x38,
        Stage_croll = 0x39,
        Stage_battles = 0x41
    };
} // namespace Stages

typedef Stages::StageKind StageKind;
